[project]
name = "py-bootstrap"
version = "0.3.4"
description = "Bootstrap your Python Package Development"
readme = "README.md"
requires-python = ">=3.13"
classifiers = [
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
]
dependencies = [ "copier-template-extensions>=0.3.3", "jinja2>=3.1.6" ]

[dependency-groups]
dev = [
  "pydantic>=2.12.5",
  "pytest>=9.0.2",
  "ruff>=0.14.9",
  "ty>=0.0.3",
  "zensical>=0.0.15",
  { include-group = "scripts" },
]
scripts = [
  "httpx>=0.28.1",
  "pydantic>=2.12.5",
]

[tool.ruff]
line-length = 88
indent-width = 4
[tool.ruff.format]
indent-style = "space"
quote-style = "double"
line-ending = "auto"
skip-magic-trailing-comma = false
docstring-code-line-length = "dynamic"
docstring-code-format = false
[tool.ruff.lint]
select = [ "ALL" ]
ignore = [
  "COM812", # missing-trailing-comma (may conflict with ruff formatter)
  "D203",   # incorrect-blank-line-before-class (conflicts with D211)
  "D213",   # multi-line-summary-second-line (conflicts with D212)
]
per-file-ignores."**/{tests}/*" = [
  "ANN001",
  "ANN201",
  "D",
  "E402",
  "INP001",
  "S101",
  "T201",
]
per-file-ignores."**/{scripts}/*" = [
  "ANN001",
  "D",
  "E402",
  "INP001",
  "S101",
  "T201",
  "TD",
]
per-file-ignores."extensions.py" = [ "D" ]
fixable = [ "ALL" ]
unfixable = []

[tool.pyproject-fmt]
table_format = "long"
collapse_tables = [ "project.authors" ]

[tool.pytest]
filterwarnings = [
  "ignore::DeprecationWarning",
  "ignore:Dirty template changes included automatically",
]

[tool.coverage.run]
relative_files = true
