Output casette.gif
Set Shell zsh
Set FontSize 32
Set Width 1200
Set Height 600

Require copier

Sleep 1s
Type 'copier copy --trust "gh:npikall/py-bootstrap" foobar'
Sleep 500ms
Enter
Sleep 1.5s
Type "foobar"
Enter
Sleep 800ms
Enter
Sleep 800ms
Enter
Sleep 800ms
Enter
Sleep 800ms
Enter
Sleep 800ms
Enter
Sleep 800ms
Enter
Sleep 800ms
Enter
Sleep 800ms
Enter
Sleep 800ms
Enter
Sleep 800ms
Enter 2
Sleep 3s

Hide
Type "rm -rf foobar/"
